require('globals')
require('options')
require('colorscheme')
require('icons')
require('lsp')
require('plugins')
vim.cmd('source ~/.config/nvim/vim/keymap.vim')
vim.cmd('source ~/.config/nvim/vim/autocmds.vim')
